### ISSUE TITLE
includePackageJsons not including package.json files in node_modules

### ISSUE THREAD

**Issue by mojave27** [sonatype-nexus-community/copy-modules-webpack-plugin#19]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
I am attempting to use the includePackageJsons configuration of copy-modules-webpack-plugin to include package.json files with the node_modules packages as created by copy-modules-webpack-plugin.

* **What feature or behavior is this required for?**
I am attempting to use the new [NIQS expanded Javascript scanning functionality](https://guides.sonatype.com/iqserver/technical-guides/scanning-js/) on a webpack project.  In order to do so, I need to include package.json files for each of the node_modules packages.

* **How could we solve this issue? (Not knowing is okay!)**
I am not sure.  Maybe an example of the config showing proper use of the includePackageJsons property.

* **Anything else?**
I am running the copy-modules-webpack-plugin on a React project, using @craco/craco.  This is the craco.config.js I am using:

```javascript
const CopyModulesPlugin = require("copy-modules-webpack-plugin")

module.exports = {
  webpack: {
    plugins: [
      new CopyModulesPlugin({
	destination: 'webpack_modules',
	includePackageJsons: true
      })
    ]
  }
};
```

I run the plugin via an npm script, which runs "craco build".

I am using 2.0.2 of copy-modules-webpack-plugin, and 4.1.0 of craco.

Listing of webpack_modules/node_modules/*/package.json:

```
$: ls webpack_modules
node_modules
src

$: ls webpack_modules/node_modules/*/package.json
ls: webpack_modules/node_modules/*/package.json: No such file or directory
```

Most likely I am missing a key step, but have been unable to identify it.

**Comment by rpokorny** [comment]
> I am using 2.0.2 of copy-modules-webpack-plugin

That feature was introduced in 2.1.0, so I recommend upgrading to a newer version.  2.1.1 is the newest.

**Comment by mojave27** [comment]
Oh, I'm a moron.  That fixed it.  Thanks @rpokorny
