### ISSUE TITLE
Hoisted dependencies are missed

### ISSUE THREAD

**Issue by lexanth** [sonatype-nexus-community/copy-modules-webpack-plugin#4]
* **What are you trying to do?**
Use this plugin in a submodule/package of a yarn workspace, where common dependencies have been hoisted

* **What feature or behavior is this required for?**
This package is in the `my-package` folder within the workspace root
`my-package` depends on a dependency which has been hoisted to the root
The relative path is therefore `../node_modules/my-dependency`
When this gets copied to `destination`, it goes to `./destination/../node_modules/my-dependency`, which is actually `./node_modules/my-dependency`, so it isn't actually in `destination`.

* **How could we solve this issue? (Not knowing is okay!)**
Change the relative path logic to defend against files higher up the tree

* **Anything else?**
Workaround - set a nested path as the destination (`./destination/my-package`)

**Comment by rpokorny** [comment]
I've just released [v1.0.3](https://github.com/sonatype-nexus-community/copy-modules-webpack-plugin/releases/tag/v1.0.3) and [v2.0.1](https://github.com/sonatype-nexus-community/copy-modules-webpack-plugin/releases/tag/v2.0.1) which I believe address this.  These changes convert `..` path segments into `__..__` path segments when creating the destination paths, so any modules pulled in from outside the current working directory will be located withing one or more layers of folders named `__..__` within the destination folder.  Can you confirm that this addresses your needs?

**Comment by rpokorny** [comment]
Given the lack of response, I assume the fix was effective.  Closing.
